version: "3.7"

services:

  server:
    build:
      dockerfile: dev.Dockerfile
    volumes:
      - ./store:/store/
      - ./server:/server/
      - /server/node_modules/
    ports:
      - 4000:4000
